apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  containers:
  - name: mycontainer
    image: centos:latest
    command: ["/bin/bash", "-c", "tail -f /dev/null"]
    volumeMounts:
    - name: myvolume
      mountPath: /mnt/data  # Adjust the mount path as per your requirement
  volumes:
  - name: myvolume
    persistentVolumeClaim:
      claimName: myclaim  # Name of the PVC you created earlier
