apiVersion: apps/v1
kind: Deployment
metadata:
  name: mypod
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mypod
  template:
    metadata:
      labels:
        app: mypod
    spec:
      containers:
      - name: mycontainer
        image: centos:latest
        command: ["/bin/bash", "-c", "tail -f /dev/null"]
        volumeMounts:
        - name: myvolume
          mountPath: /mnt/data  # Adjust the mount path as per your requirement
      volumes:
      - name: myvolume
        hostPath:
          path: /mnt/data  # Adjust the host path as per your requirement
